ludus:
  - vm_name: "{{ range_id }}-ad-dc-pokepals"
    hostname: "{{ range_id }}-DC01-pokepals"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 22
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: false
    domain:
      fqdn: pokepals.com
      role: primary-dc
  - vm_name: "{{ range_id }}-ad-win11-22h2-pokepals"
    hostname: "{{ range_id }}-WINdesk-pokepals"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    windows:
      install_additional_tools: true
      office_version: 2019
      office_arch: 64bit
    domain:
      fqdn: pokepals.com
      role: member
  - vm_name: "{{ range_id }}-kali"
    hostname: "{{ range_id }}-kali"
    template: kali-x64-desktop-template
    vlan: 99
    ip_last_octet: 13
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false