ludus:
  - vm_name: "{{ range_id }}-ad-dc-pokepals"
    hostname: "{{ range_id }}-DC01-pokepals"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 22
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: pokepals.domain
      role: primary-dc
    roles:
      - badsectorlabs.ludus_adcs
  - vm_name: "{{ range_id }}-win11-pokepals"
    hostname: "{{ range_id }}-WIN-pals"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 8
    cpus: 2
    windows:
      install_additional_tools: true
      office_version: 2019
      office_arch: 64bit
    domain:
      fqdn: pokepals.domain
      role: member
  - vm_name: "{{ range_id }}-EXC-MAIL-pokepals"
    hostname: "{{ range_id }}-mail-pokepals"
    template: win2019-server-x64-no-security-updates-template
    vlan: 20
    ip_last_octet: 2
    ram_gb: 16
    cpus: 4
    windows:
      sysprep: true
    domain:
      fqdn: ludus.domain
      role: member
    roles:
      - aleemladha.ludus_exchange
  - vm_name: "{{ range_id }}-wiki-pokepals"
    hostname: "{{ range_id }}-wiki-pokepals"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 80
    ram_gb: 8
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - badsectorlabs.ludus_vulhub
    role_vars:
      vulhub_envs:
        - confluence/CVE-2023-22527
    domain:
      fqdn: pokepals.domain
      role: member
  - vm_name: "{{ range_id }}-wp-pokepals"
    hostname: "{{ range_id }}-wp-pokepals"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 81
    ram_gb: 4
    cpus: 1
    linux: true
    testing:
      snapshot: false
      block_internet: false
    roles:
      - badsectorlabs.ludus_vulhub
    role_vars:
      vulhub_envs:
        - wordpress/pwnscriptum
    domain:
      fqdn: pokepals.domain
      role: member
  - vm_name: "{{ range_id }}-db-pokepals"
    hostname: "{{ range_id }}-db-pokepals"
    template: ubuntu-22.04-x64-server-template
    vlan: 10
    ip_last_octet: 82
    ram_gb: 4
    cpus: 1
    linux: true
    testing:
      snapshot: false
      block_internet: false
    domain:
      fqdn: pokepals.domain
      role: member
  - vm_name: "{{ range_id }}-scoreengine"
    hostname: "{{ range_id }}-scoreengine"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 95
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false
    domain:
      fqdn: pokepals.domain
      role: member

network:
  inter_vlan_default: REJECT
  rules:
    - name: Only allow windows to kali on 443
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 443
      action: ACCEPT
    - name: Only allow windows to kali on 80
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 80
      action: ACCEPT
    - name: Only allow windows to kali on 8080
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 8080
      action: ACCEPT
    - name: Allow kali to all windows
      vlan_src: 99
      vlan_dst: 10
      protocol: all
      ports: all
      action: ACCEPT
    - name: Allow ScoreEngine to all windows
      vlan_src: 10
      vlan_dst: 10
      protocol: all
      ports: all
      action: ACCEPT
