ludus:
  - vm_name: "{{ range_id }}-SE-pokepals"
    hostname: "{{ range_id }}-SE-pokepals"
    template: debian-12-x64-server-template
    vlan: 10
    ip_last_octet: 81
    ram_gb: 4
    cpus: 2
    linux: true
    testing:
      snapshot: false
      block_internet: false